=== Missouri-BMI/i2b2-core-server/edu.harvard.i2b2.xml/xsd/cell/crc/psm_1.1/CRC.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:crc="http://www.i2b2.org/xsd/cell/crc/psm/1.1/"
    xmlns:pdo="http://www.i2b2.org/xsd/hive/pdo/1.1/"
    targetNamespace="http://www.i2b2.org/xsd/cell/crc/psm/1.1/">

    <xs:element name="request" type="crc:requestType"/>
    <xs:element name="set_job" type="crc:jobType"/>
    <xs:element name="get_all_job" type="crc:jobsType"/>
    <xs:element name="get_name_info" type="crc:findBy_childType" />
   
   <!--  
	<xs:element name="get_all_jobs" type="crc:get_jobsType"/> 
	<xs:element name="get_dblookup" type="crc:get_dblookupType"/> 
	<xs:element name="set_dblookup" type="crc:set_dblookupType"/> 
	<xs:element name="delete_dblookup" type="crc:delete_dblookupType"/>                         
    -->
    
    <xs:element name="sql" type="xs:string"/>
    
    
    <xs:complexType name="paramType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" />
				<xs:attribute name="id" type="xs:int" />
				<xs:attribute name="datatype" type="xs:string" />				
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
    
    <xs:complexType name="paramsType">
		<xs:sequence>
			<xs:element name="param" type="crc:paramType" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
	</xs:complexType>	
    
    <xs:complexType name="jobsType">
		<xs:sequence>
			<xs:element name="job" type="crc:jobType" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

               
    <xs:complexType name="jobType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="group" type="xs:string" />
			<xs:element name="schedule" type="crc:scheduleType" />
            <xs:element name="start_time" type="xs:dateTime"/>
            <xs:element name="end_time" type="xs:dateTime"/>
			<xs:element name="status" type="xs:string" />            
            <xs:element name="message" type="xs:string"/>	
            <xs:element name="param" type="crc:paramType" minOccurs="0"
				maxOccurs="unbounded" />    		
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:element name="jobs" type="crc:jobsType"/><!-- swc20160523 added -->      

	
	<xs:complexType name="scheduleType">
		<xs:sequence>
			<xs:element name="repeat" type="xs:string" />
			<xs:element name="intervalIn" type="xs:string" />
			<xs:element name="Interval" type="xs:int" />
		</xs:sequence>
	</xs:complexType>
	               
    <xs:complexType name="requestType" abstract="true">
        <xs:annotation>
            <xs:documentation>requestType is abstract so a concrete type must be declared in the
                instance document using the xsi:type attribute.</xs:documentation>
        </xs:annotation>
        <xs:sequence/>
    </xs:complexType>
    
    
  <xs:complexType name="findBy_childType">
        <xs:sequence>
            <xs:element name="match_str" type="crc:match_strType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="create_date" type="xs:dateTime" minOccurs="0"/>
            <xs:element name="user_id" type="xs:string"/>
        	<xs:element name="ascending" type="xs:boolean" default="false"/>            
        </xs:sequence>
        <xs:attribute name="max" type="xs:int" use="required"/>
        <xs:attribute name="category" default="top">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="@"/>
                    <xs:enumeration value="top"/>
                    <xs:enumeration value="results"/>
                    <xs:enumeration value="pdo"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
     </xs:complexType>
    

    
        <xs:complexType name="match_strType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="strategy" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="exact"/>
                            <xs:enumeration value="left"/>
                            <xs:enumeration value="right"/>
                            <xs:enumeration value="contains"/>
                           
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>    
    

    <xs:complexType name="headerType">
        <xs:sequence>
            <xs:element name="user" type="crc:userType"/>
            <xs:element name="data_source" type="xs:string"/>
            <xs:element name="patient_set_limit" type="xs:int"/>
            <xs:element name="estimated_time" type="xs:int"/>
            <xs:element name="create_date" type="xs:dateTime"/>
            <xs:element name="submit_date" type="xs:dateTime"/>
            <xs:element name="complete_date" type="xs:dateTime"/>
             <xs:element name="query_mode" type="crc:queryModeType"/>
            <!-- <xs:element name="request_type" type="crc:request_typeType"/> -->
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="userType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="login" type="xs:string" use="required"/>
                <xs:attribute name="group" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    
    <xs:simpleType name="limitType">
        <xs:restriction base="xs:int"/>
    </xs:simpleType>

    <xs:simpleType name="queryModeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="optimize_without_temp_table"/>
            <xs:enumeration value="count_min_sketch"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Missouri-BMI/i2b2-core-server/edu.harvard.i2b2.xml/xsd/cell/crc/psm_1.1/CRC.xml
<?xml version="1.0" encoding="UTF-8"?>
<crc:set_job xmlns:crc="http://www.i2b2.org/xsd/cell/crc/psm/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.i2b2.org/xsd/cell/crc/psm/1.1/ CRC.xsd ">
  <name>name</name>
  <group>group</group>
  <schedule>
    <repeat>repeat</repeat>
    <intervalIn>intervalIn</intervalIn>
    <Interval>0</Interval>
  </schedule>
  <start_time>2001-12-31T12:00:00</start_time>
  <end_time>2001-12-31T12:00:00</end_time>
  <status>status</status>
  <message>message</message>
</crc:set_job>
